blog/urls.py
from django.urls import path,include
from . import views
from . import api_views
from .api_views import PostListCreateView, PostDetailView, CategoryListView, TagListView, CommentListCreateView, CommentDetailView
from rest_framework import routers
from rest_framework.routers import DefaultRouter



app_name = 'blog'


urlpatterns = [
   

    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('/post', views.PostCreateView.as_view(), name='post'),
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('<int:pk>/comment/', views.AddCommentToPostView.as_view(), name='add_comment_to_post'),
    # ----------------------------------------------------------------------------
    path('api/posts/', PostListCreateView.as_view(), name='post-list-create-api'),
    path('api/posts/<int:pk>/', PostDetailView.as_view(), name='post--api'),
    path('api/categories/', CategoryListView.as_view(), name='category-list'),
    path('api/tags/', TagListView.as_view(), name='tag-list'),
    path('api/comments/', CommentListCreateView.as_view(), name='comment-list-create'),
    path('api/comments/<int:pk>/', CommentDetailView.as_view(), name='comment-detail'),



    
 
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('blog/' , include('blog.urls' , namespace='blog')),
    path('' , include('blog.urls' , namespace='home')),
    path('accounts/api/registration/', include('dj_rest_auth.registration.urls')),
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils.text import slugify


class Post(models.Model):
    author = models.ForeignKey(User,related_name='post_author' , on_delete=models.CASCADE ,)
    title = models.CharField(max_length=50 )
    content = models.TextField(max_length=10000)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at=models.DateTimeField(default=timezone.now)
    category = models.ForeignKey('Category', related_name='post_category', on_delete=models.CASCADE )
    tags = TaggableManager(blank=True)
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
       if not self.slug:
           self.slug = slugify(self.title)    
       super(Post, self).save(*args, **kwargs) # Call the real save() method


       

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})



class Category(models.Model):
    name = models.CharField(max_length=25)
    slug = models.SlugField(blank=True, null=True)


    def save(self, *args, **kwargs):
       if not self.slug:
           self.slug = slugify(self.name)    
       super(Category, self).save(*args, **kwargs) # Call the real save() method

        

    def __str__(self):
        return self.name

class Comment(models.Model):
    author = models.ForeignKey(User,related_name='comment_author' , on_delete=models.CASCADE ,)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)


    def __str__(self):
        return self.content

blog/forms.py
# blog_app/forms.py

from django import forms
from .models import Post, Comment
from taggit.forms import TagWidget

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'tags']
        widgets = {
            'tags': TagWidget(),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormView
from django.core.paginator import Paginator
from .models import Post, Category, Comment
from .forms import PostForm, CommentForm
from taggit.models import Tag
from django.db.models import Count, Q
from django.urls import reverse
from django.views import View
from django.urls import reverse_lazy

class PostListView(LoginRequiredMixin,ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] =  Tag.objects.all()
        context['categories'] = Category.objects.all().annotate(post_count=Count('post_category'))
        return context

    def get_queryset(self):
        queryset = Post.objects.all()
        search_query = self.request.GET.get('q')

        if search_query:
            queryset = queryset.filter(title__icontains=search_query) | queryset.filter(content__icontains=search_query)

        return queryset

    # def get_queryset(self):
    #     name = self.request.GET.get('q','')
        
    #     object_list = Post.objects.filter(
    #         Q(title__icontains=name) | 
    #         Q(content__icontains=name)
    #     )
    #     return object_list
    

class PostDetailView(DetailView):
    model = Post
   

class PostCreateView(LoginRequiredMixin,CreateView):  
    model = Post 
    template_name = 'blog/post_create.html'
    fields = '__all__' 
    success_url ='/blog'

class PostUpdateView(LoginRequiredMixin,UpdateView):  
    model = Post 
    template_name = 'blog/post_edit.html'
    fields = '__all__' 
    success_url =reverse_lazy('blog:post_list')



class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/blog'
    template_name = 'blog/post_confirm_delete.html'


class AddCommentToPostView(LoginRequiredMixin, View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = CommentForm()
        return render(request, 'blog/add_comment_to_post.html', {'form': form})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect(post.get_absolute_url())
        return render(request, 'blog/add_comment_to_post.html', {'form': form})

blog/templates/blog/add_comment_to_post.html
<!-- blog/add_comment_to_post.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Add a comment to "{{ post.title }}"</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Comment</button>
  </form>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete the post titled "{{ object.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
    </form>
</div>

{% endblock %}

blog/templates/blog/post_create.html
{% extends "base.html" %}
<h2>Create New Post</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create New Post">
</form>


<!-- blog_app/templates/blog_app/post_create.html -->

{% block title %}Create Post{% endblock %}

{% block content %}
  <h1>Create New Post</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Create</button>
  </form>
  <a href="{% url 'blog:post_list' %}" class="btn btn-secondary mt-2">Back to Posts</a>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %} 
{% load static %}


{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>{{ post.title }}</h1>
        <p>By {{ post.author.username }} on {{ post.created_at }}</p>
        <p>{{ post.content }}</p>
        <a href="{% url 'blog:post_update' post.pk %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-danger">Delete</a>
    </div>
</div>
<div class="row mt-4">
    <div class="col-md-12">
        <h2>Comments</h2>
        <ul class="list-group">
            {% for comment in post.comment_set.all %}
            <li class="list-group-item">
                <p>{{ comment.content }}</p>
                <p>By {{ comment.author }} on {{ comment.created_at }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div class="row mt-4">
    <div class="col-md-12">
        <h2>Add a Comment</h2>
        <form method="post" action="{% url 'blog:add_comment_to_post' post.pk %}">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit" class="btn btn-success">Add Comment</button>
        </form>
    </div>
</div>


  

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h2>Edit Post</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit Post">
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %}
{% comment %} 

{% block title %}Post List{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h1>Posts</h1>
        <form method="get" action=".">
            <input type="text" name="q" placeholder="Search...">
            <button type="submit">Search</button>
        </form>
        <ul class="list-group">
            {% for post in posts %}
            <li class="list-group-item">
                <h2><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
                <p>By {{ post.author.username }} on {{ post.created_at }}</p>
                <p>{{ post.content|truncatewords:30 }}</p>
                <p>{{ post.category }}</p>
                <p>{{ post.slug}}</p>
                <a href="{% url 'blog:post_update' post.pk %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-danger">Delete</a>
            </li>
            {% endfor %}
        </ul>
     
        {% if is_paginated %}
            <div class="row mt-5">
                <div class="col text-center">
                    <div class="block-27">
                        <ul>
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                            {% else %}
                                <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}

                            {% for i in paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="active"><span>{{ i }}</span></li>
                                {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                            {% else %}
                                <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}  {% endcomment %}


{% block title %}Post List{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h1>Posts</h1>
        <form method="get" action=".">
            <input type="text" name="q" placeholder="Search...">
            <button type="submit">Search</button>
        </form>
        <ul class="list-group">
            {% for post in posts %}
            <li class="list-group-item">
                <h2><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
                <p>By {{ post.author.username }} on {{ post.created_at }}</p>
                <p>{{ post.content|truncatewords:30 }}</p>
                <p>{{ post.category }}</p>
                <p>{{ post.slug}}</p>
                <a href="{% url 'blog:post_update' post.pk %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-danger">Delete</a>
            </li>
            {% endfor %}
        </ul>
     
        {% if is_paginated %}
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                        {% endif %}

                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active"><span class="page-link">{{ i }}</span></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ paginator.num_pages }}">&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}
    </div>
</div>
{% endblock %}